export { ReactComponent as SearchIcon } from './search.svg'
export { ReactComponent as HomeIcon } from './home.svg'
export { ReactComponent as HamburgerIcon } from './hamburger.svg'
export { ReactComponent as ChartIcon } from './pie-chart.svg'
export { ReactComponent as LogoIcon } from './logo.svg'
export { ReactComponent as TimeIcon } from './access_time.svg'
